spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:52514/queshen?useUnicode=true&useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: localhost
    password: localhost
  redis:
    host: localhost
    port: 52515
    password: localhost
    # 连接池配置
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        time-between-eviction-runs: 100s
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: root
#    password: root
#  data:
#    mongodb:
#      database: mahjong
#      host: root
#      password: root
#      username: root
#      port: 27017
#      authentication-database: admin
#      auto-index-creation: false
  #Servlet配置信息
  servlet:
    multipart:
      #最大传输 MultipartFile 大小 和 最大请求大小
      max-file-size: 10MB
      max-request-size: 10MB
#小程序信息
wechat:
  appid: wx96localhost0a291dc
  secret: bae673localhost91732de442

wx:
  pay:
    appId: wx9localhost291dc #微信公众号或者小程序等的appid
    mchId: 163localhost00 #微信支付商户号
    mchKey: Mjmk152localhostiinju741f #微信支付商户密钥
    #    subAppId: #服务商模式下的子商户公众账号ID
    #    subMchId: #服务商模式下的子商户号
    keyPath: classpath:apiclient_cert.p12
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）