spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:52514/queshen?useUnicode=true&useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 53433
    password: u*******/r+
    # 连接池配置
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        time-between-eviction-runs: 100s
#  rabbitmq:
#    host: 43.143.88.250
#    port: 5672
#    username: wwx@
#    password: wwx@
  data:
    mongodb:
      database: mahjong
      host: root
      password: root
      username: root
      port: 27017
      authentication-database: admin
      auto-index-creation: false
  #Servlet配置信息
  servlet:
    multipart:
      #最大传输 MultipartFile 大小 和 最大请求大小
      max-file-size: 10MB
      max-request-size: 10MB
#小程序信息
wechat:
  appid: wx934543455691dc
  secret: bae67345435345342de442

wx:
  pay:
    appId: wx934535345291dc #微信公众号或者小程序等的appid
    mchId: 163434534500 #微信支付商户号
    mchKey: Mjmk1523453453434533454钥
    #    subAppId: #服务商模式下的子商户公众账号ID
    #    subMchId: #服务商模式下的子商户号
    keyPath: classpath:apiclient_cert.p12
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）